### ISSUE TITLE
Cannot Install package

### ISSUE THREAD

**Issue by heberbrandao** [carbonfact/icanexplain#4]
Hey team, I followed your talk on PyData and I would love to test this library. However, we are facing issues installing it.

Currently we are developing on Databricks on a Python3.9 version, and we have been getting the same error over and over after running `%pip install icanexplain`

`ERROR: Could not find a version that satisfies the requirement icanexplain (from versions: none)
ERROR: No matching distribution found for icanexplain
CalledProcessError: Command 'pip --disable-pip-version-check install icanexplain' returned non-zero exit status 1.`

Any ideas how we can fix that?

**Comment by MaxHalford** [comment]
Hey there! Thanks for the interest :)

Actually I guess this is because I configured Python to be >=3.11. Let me see if I can loosen this.

**Comment by MaxHalford** [comment]
Ok @heberbrandao I published a new version of the package. The good news is that it supports Python 3.10 and above. The bad news is that I can't push it down to Python 3.9 because Ibis requires Python 3.10 and above...
